require("config.lsp")
require("config.treesitter")
require("config.editor")
require("config.search")
require("config.vision")
require("config.git")
require("config.keymaps")
require("config.project")
